FROM httpd:2.4
RUN apt update
RUN apt install openssl
RUN openssl req -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out /usr/local/apache2/conf/server.crt -keyout /usr/local/apache2/conf/server.key -subj "/C=US/ST=NY/L=Rochester/O=RIT/OU=CSEC731/CN=www.dockerdemo.com"
EXPOSE 443
